### PR TITLE
	modified:   pydlm/dlm.py

### PR DESCRIPTION
**Pull request by DeliciousHair**
* fixed annoying typo: fitering --> filtering
* added ability to set `_defaultOptions(**options)` when instantiating `dlm` class

### CODE REVIEW

**Review by wwrechard — CHANGES_REQUESTED** [review]
Hey, thanks for the change! It seems the PR breaks tests on Python 2.7 because of using `super()`.

Could you please fix the tests so that I can merge the PR? A million thanks!

**Comment by DeliciousHair** [comment]
Heyo!

I don't actually know how to use the 'old-style' classes, and I don't even have a 2.7 environment on hand at the moment. What I've done is modified the `_dlm` class via:
```
class _dlm(object):
```
which should fix things. I hope.

**Comment by DeliciousHair** [comment]
~~Well that didn't seem to work... Will set up a 2.7 environment and sort this out later in the week.~~

Success!

**Review by wwrechard — APPROVED** [review]
Thanks for the change!

**Pull request merged**
