### PR TITLE
Remove >>> for easier copy and testing

### PR DESCRIPTION
**Pull request by xgdgsc**
Remove >>> for easier copy and testing.

### CODE REVIEW

**Comment by xgdgsc** [comment]
You should do the same with rst docs.

**Review by wwrechard — COMMENTED** [review]
Could merge the three commits into one?

Thanks!

**Comment by xgdgsc** [comment]
https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits . Seems you can do that.

**Review by wwrechard — APPROVED** [review]
LGTM

Thanks!

**Pull request merged**
